# Site settings

# update config
#
# Modified by tLLWtG

title: tLLWtG Blog
SEOTitle: Sliverkiss Blog | Sliverkiss 的博客
# bg changed to random
header-img: img/home-bg.jpg
email: tistzach@gmail.com
description: "这里是 Sliverkiss 的个人博客，与你一起发现更大的世界 | 相遇即是缘分～"
keyword: "tLLWtG, tLLWtG 的博客, tLLWtG Blog, 博客, 个人网站, 互联网, Web"
url: "https://sliverkiss.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# start-time (yyyy-mm-dd)
start_time: "2023-05-17"

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
# weibo_username: tLLWtG
# zhihu_username: tllwtg
github_username: [Sliverkiss](https://www.github.com/sliverkiss)
# twitter_username: tistzach
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 7
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
    "vendor",
  ]
anchorjs: false # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
#plugins: [jekyll-paginate] (move to the bottom)

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings edited
#disqus_username: hux

# giscus
giscus: true

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics edited
#ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "一名乐观的虚无主义者 <br>"
sidebar-avatar: https://avatars.githubusercontent.com/u/70052878 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "tLLWtG Blog, but with Hexo", href: "https://hexo.tllwtg.top" },
    { title: "镜像站", href: "https://mirror.tllwtg.top" },
    { title: "OI Wiki", href: "https://oi.wiki" },
    { title: "Codeforces", href: "https://codeforces.com" },
    { title: "洛谷", href: "https://www.luogu.com.cn" },
    { title: "一言", href: "https://hitokoto.cn" },
  ]

# added sitemap
plugins:
  - jekyll-sitemap
  - jekyll-paginate
